__author__ = "Michal Szpunar"


from src.id3_tree import Id3DecisionTree
import csv


class C45DecisionTree:
    def __init__(self,  dataframe, omega, R = None, path=None):
        assert R is not None or path is not None
        if R:  # R is a list of tuples generated by RegexGenerator
            self.tree = Id3DecisionTree(R=R, dataframe=dataframe, omega=omega)

        elif path:  # path is a path to csv file with regexes
            with open(path) as f:
                R = [tuple(line) for line in csv.reader(f)]
                del R[0]
                for r in R:
                    if not r:
                        R.remove(r)  # deleting empty rows
                self.tree = Id3DecisionTree(R=R, dataframe=dataframe, omega=omega)

        if omega:  # if omega == 0, skip trimming
            self.c4_5()
        self.train_accuracies = None
        self.test_accuracies = None

    def trim(self, node):
        # print(f'NODE: {node.debug_name}')
        if not node.parent:
            return
        if node not in self.tree.nodes:
            pass
        if not node.leaf:
            leaf = node.to_leaf()
            e0 = self.tree.subtree_test_error_estimate(node)
            e1 = self.tree.subtree_test_error_estimate(leaf)

            if e0 >= e1:
                # search for children of a node and delete all of them
                children = []
                Id3DecisionTree.search_children(node, children)
                for c in children:
                    self.tree.nodes.remove(c)
                    if c.leaf:
                        self.tree.leaves.remove(c)

                node.leaf = True
                node.label = leaf.label
                self.tree.leaves.append(node)
        self.trim(node.parent)

    def c4_5(self):
        i = 0
        for leaf in self.tree.leaves:
            print(f'c4.5 progress: LEAF {i} OUT OF {len(self.tree.leaves)}')
            self.trim(leaf)
            i += 1

    def evaluate(self, data):
        acc = self.tree.evaluate_accuracy(self.tree, data)
        acc1 = Id3DecisionTree.evaluate_label_accuracy(self.tree, data, label=1)
        acc0 = Id3DecisionTree.evaluate_label_accuracy(self.tree, data, label=0)

        return acc, acc1, acc0

    def evaluate_accuracies(self, test_data):
        self.train_accuracies = self.evaluate(self.tree.S)
        self.test_accuracies = self.evaluate(test_data.to_dict('records'))

    def show_test_accuracies(self):
        print(f'TOTAL TEST ACCURACY: {self.test_accuracies[0]}')
        print(f'TEST ACCURACY OF ONES: {self.test_accuracies[1]}')
        print(f'TEST ACCURACY OF ZEROS: {self.test_accuracies[2]}')

    def show_train_accuracies(self):
        print(f'TOTAL TRAIN ACCURACY: {self.train_accuracies[0]}')
        print(f'TRAIN ACCURACY OF ONES: {self.train_accuracies[1]}')
        print(f'TRAIN ACCURACY OF ZEROS: {self.train_accuracies[2]}')

    def show_leaves_num(self):
        one_counter = 0
        for n in self.tree.leaves:
            if n.label == 1:
                one_counter += 1
        zero_counter = len(self.tree.leaves) - one_counter
        print(f'NUM OF "0" LEAVES: {zero_counter}')
        print(f'NUM OF "1" LEAVES: {one_counter}')

    def predict(self, record):
        return self.tree.get_prediction(self.tree.root, record)












